# Generated by Django 5.1.15 on 2026-01-14 20:15

import django.db.models.deletion
import prose.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    def migrate_types_to_subclasses(apps, schema_editor):
        """migrate annotation_type to relevant BaseAnnotation subclass"""
        TextAnnotation = apps.get_model("textannotation", "TextAnnotation")
        TextualVariant = apps.get_model("textannotation", "TextualVariant")
        EditorialNote = apps.get_model("textannotation", "EditorialNote")
        CrossReference = apps.get_model("textannotation", "CrossReference")

        editorial_notes = []
        cross_references = []
        textual_variants = []

        for ann in TextAnnotation.objects.all():
            annotation_fields = {
                "content_type": ann.content_type,
                "object_id": ann.object_id,
                "from_pos": ann.from_pos,
                "to_pos": ann.to_pos,
                "selected_text": ann.selected_text,
                "annotation": ann.annotation,
            }
            if ann.annotation_type == "note":
                editorial_notes.append(EditorialNote(**annotation_fields))
            elif ann.annotation_type == "reference":
                cross_references.append(CrossReference(**annotation_fields))
            elif ann.annotation_type == "variant":
                textual_variants.append(TextualVariant(**annotation_fields))

        EditorialNote.objects.bulk_create(editorial_notes)
        CrossReference.objects.bulk_create(cross_references)
        TextualVariant.objects.bulk_create(textual_variants)

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("manuscript", "0116_alter_linecode_options_and_more"),
        ("textannotation", "0003_alter_textannotation_annotation_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "from_pos",
                    models.JSONField(
                        default=dict,
                        help_text="ProseMirror position data for annotation start",
                    ),
                ),
                (
                    "to_pos",
                    models.JSONField(
                        default=dict,
                        help_text="ProseMirror position data for annotation end",
                    ),
                ),
                ("selected_text", models.TextField(default="")),
                (
                    "annotation",
                    prose.fields.RichTextField(
                        blank=True, help_text="Enter your annotation here", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EditorialNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "from_pos",
                    models.JSONField(
                        default=dict,
                        help_text="ProseMirror position data for annotation start",
                    ),
                ),
                (
                    "to_pos",
                    models.JSONField(
                        default=dict,
                        help_text="ProseMirror position data for annotation end",
                    ),
                ),
                ("selected_text", models.TextField(default="")),
                (
                    "annotation",
                    prose.fields.RichTextField(
                        blank=True, help_text="Enter your annotation here", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TextualVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "from_pos",
                    models.JSONField(
                        default=dict,
                        help_text="ProseMirror position data for annotation start",
                    ),
                ),
                (
                    "to_pos",
                    models.JSONField(
                        default=dict,
                        help_text="ProseMirror position data for annotation end",
                    ),
                ),
                ("selected_text", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotation",
                    prose.fields.RichTextField(
                        blank=True, null=True, verbose_name="Variant text"
                    ),
                ),
                (
                    "variant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique identifier for each variant",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "significance",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3")], default=0
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("editor_initials", models.CharField(blank=True, max_length=10)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="manuscript.singlemanuscript",
                        verbose_name="Manuscript (siglum)",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            migrate_types_to_subclasses, reverse_code=migrations.RunPython.noop
        ),
        migrations.AddIndex(
            model_name="crossreference",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="textannotat_content_0aeb82_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="editorialnote",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="textannotat_content_ec7499_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="textualvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("significance__in", [0, 1, 2, 3])),
                name="significance_valid_range",
            ),
        ),
        migrations.DeleteModel(
            name="TextAnnotation",
        ),
    ]
