# Generated by Django 5.1.15 on 2026-01-14 22:14

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textannotation", "0004_crossreference_editorialnote_textualvariant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textualvariant",
            name="notes",
            field=prose.fields.RichTextField(blank=True, null=True),
        ),
    ]
