# Generated by Django 5.1.15 on 2026-02-05 19:15

import wagtail.fields
from django.db import migrations, models


def populate_manuscripts_introduction(apps, schema_editor):
    ManuscriptsIntroduction = apps.get_model("pages", "ManuscriptsIntroduction")
    ManuscriptsIntroduction.objects.get_or_create(
        title="Manuscripts",
        body="This is an index of all of the manuscripts catalogued by the project that contain <em>La sfera</em>, with links to metadata and digitized materials.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_homeintroduction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManuscriptsIntroduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", wagtail.fields.RichTextField()),
            ],
        ),
        migrations.RunPython(
            populate_manuscripts_introduction, migrations.RunPython.noop
        ),
    ]
