# Generated by Django 5.1.15 on 2026-02-17 21:35

import wagtail.fields
from django.db import migrations


def migrate_to_streamfield(apps, schema_editor):
    # migrate RichTextField body fields content to new StreamField
    AboutPage = apps.get_model("pages", "AboutPage")
    SitePage = apps.get_model("pages", "SitePage")
    HomeIntroduction = apps.get_model("pages", "HomeIntroduction")

    for Model in [AboutPage, SitePage, HomeIntroduction]:
        for obj in Model.objects.all():
            old_field_name = f"old_body"
            raw_html = getattr(obj, old_field_name)
            if raw_html:
                # just attach everything as a paragraph for simplicity
                stream_data = [{"type": "paragraph", "value": raw_html}]
                setattr(obj, "body", stream_data)
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_manuscriptsintroduction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutpage",
            old_name="body",
            new_name="old_body",
        ),
        migrations.RenameField(
            model_name="homeintroduction",
            old_name="body",
            new_name="old_body",
        ),
        migrations.RenameField(
            model_name="sitepage",
            old_name="body",
            new_name="old_body",
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("heading", 1), ("image", 2), ("video", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    1: ("wagtail.blocks.CharBlock", (), {"icon": "title"}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"icon": "image", "template": "partials/image_block.html"},
                    ),
                    3: ("wagtail.embeds.blocks.EmbedBlock", (), {"icon": "media"}),
                },
            ),
        ),
        migrations.AddField(
            model_name="homeintroduction",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("heading", 1), ("image", 2), ("video", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    1: ("wagtail.blocks.CharBlock", (), {"icon": "title"}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"icon": "image", "template": "partials/image_block.html"},
                    ),
                    3: ("wagtail.embeds.blocks.EmbedBlock", (), {"icon": "media"}),
                },
            ),
        ),
        migrations.AddField(
            model_name="sitepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("heading", 1), ("image", 2), ("video", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    1: ("wagtail.blocks.CharBlock", (), {"icon": "title"}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"icon": "image", "template": "partials/image_block.html"},
                    ),
                    3: ("wagtail.embeds.blocks.EmbedBlock", (), {"icon": "media"}),
                },
            ),
        ),
        migrations.RunPython(migrate_to_streamfield, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="aboutpage",
            name="old_body",
        ),
        migrations.RemoveField(
            model_name="homeintroduction",
            name="old_body",
        ),
        migrations.RemoveField(
            model_name="sitepage",
            name="old_body",
        ),
    ]
