# Generated by Django 5.1.15 on 2026-02-17 22:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_rename_body_aboutpage_old_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("heading", 1), ("image", 4), ("video", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    1: ("wagtail.blocks.CharBlock", (), {"icon": "title"}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional caption for the image",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"icon": "media", "max_height": 400, "max_width": 800},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homeintroduction",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("heading", 1), ("image", 4), ("video", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    1: ("wagtail.blocks.CharBlock", (), {"icon": "title"}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional caption for the image",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"icon": "media", "max_height": 400, "max_width": 800},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="sitepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("heading", 1), ("image", 4), ("video", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    1: ("wagtail.blocks.CharBlock", (), {"icon": "title"}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional caption for the image",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"icon": "media", "max_height": 400, "max_width": 800},
                    ),
                },
            ),
        ),
    ]
