# Generated by Django 5.1.15 on 2026-02-19 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_alter_aboutpage_body_alter_homeintroduction_body_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPage",
            fields=[
                (
                    "sitepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pages.sitepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("pages.sitepage",),
        ),
    ]
