# Generated by Django 5.1.15 on 2026-04-23 17:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_datapage"),
    ]

    operations = [
        migrations.AddField(
            model_name="datapage",
            name="additional_resources",
            field=wagtail.fields.StreamField(
                [("link", 2), ("document", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text to display for the link", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "URL", "required": True},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("title", 0), ("url", 1)]], {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Override the document's original filename",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("document", 4)]],
                        {},
                    ),
                },
            ),
        ),
    ]
