# Generated by Django 5.1.15 on 2026-04-24 15:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_datapage_additional_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeintroduction',
            name='navigation_cards',
            field=wagtail.fields.StreamField([('card', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'The title text that will appear in the card (e.g. Edition)', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'The subtitle text that will appear in the card', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "The URL for the 'More' link", 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('url', 3)]], {})}, help_text='The cards with links that appear below the intro text'),
        ),
    ]
