# Generated by Django 5.1.15 on 2026-08-31 17:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_homeintroduction_navigation_cards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("heading", 1),
                    ("image", 4),
                    ("video", 5),
                    ("quote", 6),
                    ("accordion", 9),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    1: ("wagtail.blocks.CharBlock", (), {"icon": "title"}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional caption for the image",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"icon": "media", "max_height": 400, "max_width": 800},
                    ),
                    6: ("wagtail.blocks.BlockQuoteBlock", (), {"icon": "openquote"}),
                    7: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    8: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("content", 8)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homeintroduction",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("heading", 1),
                    ("image", 4),
                    ("video", 5),
                    ("quote", 6),
                    ("accordion", 9),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    1: ("wagtail.blocks.CharBlock", (), {"icon": "title"}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional caption for the image",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"icon": "media", "max_height": 400, "max_width": 800},
                    ),
                    6: ("wagtail.blocks.BlockQuoteBlock", (), {"icon": "openquote"}),
                    7: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    8: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("content", 8)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="sitepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("heading", 1),
                    ("image", 4),
                    ("video", 5),
                    ("quote", 6),
                    ("accordion", 9),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    1: ("wagtail.blocks.CharBlock", (), {"icon": "title"}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional caption for the image",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"icon": "media", "max_height": 400, "max_width": 800},
                    ),
                    6: ("wagtail.blocks.BlockQuoteBlock", (), {"icon": "openquote"}),
                    7: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    8: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("content", 8)]],
                        {},
                    ),
                },
            ),
        ),
    ]
