# Generated by Django 5.1.15 on 2026-01-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0116_alter_linecode_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StanzaVariant",
        ),
    ]
