# Generated by Django 5.1.15 on 2026-01-21 21:37

from django.db import migrations, models


def populate_rubrics(apps, schema_editor):
    # populate Stanza and StanzaTranslated line records for rubrics (xx.yy.00)
    Stanza = apps.get_model("manuscript", "Stanza")
    StanzaTranslated = apps.get_model("manuscript", "StanzaTranslated")

    all_stanzas = Stanza.objects.exclude(stanza_line_code_starts__isnull=True).values(
        "id", "stanza_line_code_starts"
    )

    processed = set()

    for entry in all_stanzas:
        code = entry["stanza_line_code_starts"]
        parts = code.split(".")
        if len(parts) != 3:
            continue

        # produce line code for rubric
        book, stanza_num, line = parts[0], parts[1], parts[2]
        stanza_key = f"{book}.{stanza_num}"
        rubric_linecode = f"{stanza_key}.00"

        # ensure we only hit one line per stanza / don't create dupes
        if stanza_key in processed:
            continue
        processed.add(stanza_key)
        if Stanza.objects.filter(stanza_line_code_starts=rubric_linecode).exists():
            continue

        # attempt to strip leading zeros by converting to int, then back to string
        try:
            display_text = f"{int(stanza_num)}."
        except ValueError:
            display_text = f"{stanza_num}."

        # attach this header to a folio, so it will appear in manuscript view
        sibling = Stanza.objects.filter(
            stanza_line_code_starts__startswith=f"{stanza_key}."
        ).first()
        sibling_folios = []
        lang = "en"

        if sibling:
            sibling_folios = list(sibling.folios.all())
            lang = sibling.language

        # create stanza
        new_stanza = Stanza.objects.create(
            stanza_line_code_starts=rubric_linecode,
            stanza_text=display_text,
            language=lang,
            is_rubric=True,
        )
        if sibling_folios:
            new_stanza.folios.set(sibling_folios)

        # create StanzaTranslated
        StanzaTranslated.objects.create(
            stanza=new_stanza,
            stanza_line_code_starts=rubric_linecode,
            stanza_text=display_text,
            language="en",
            is_rubric=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0118_strip_outer_div_from_stanza_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="stanza",
            name="is_rubric",
            field=models.BooleanField(
                default=False, help_text="Designates this stanza as a rubric/header."
            ),
        ),
        migrations.AddField(
            model_name="stanzatranslated",
            name="is_rubric",
            field=models.BooleanField(
                default=False, help_text="Designates this stanza as a rubric/header."
            ),
        ),
        migrations.RunPython(populate_rubrics, migrations.RunPython.noop),
    ]
