# Generated by Django 5.1.15 on 2026-01-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0119_stanza_is_rubric_stanzatranslated_is_rubric"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stanza",
            options={"ordering": ("stanza_line_code_starts",)},
        ),
        migrations.AlterModelOptions(
            name="stanzatranslated",
            options={
                "ordering": ("stanza_line_code_starts",),
                "verbose_name": "Stanza translation",
                "verbose_name_plural": "Stanza translations",
            },
        ),
    ]
