# Generated by Django 5.1.15 on 2026-01-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0120_alter_stanza_options_alter_stanzatranslated_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManuscriptFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "manuscripts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="family",
                        to="manuscript.singlemanuscript",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manuscript Family",
                "verbose_name_plural": "Manuscript Families",
                "ordering": ["name"],
            },
        ),
    ]
