# Generated by Django 5.1.15 on 2026-01-30 15:56

from django.db import migrations

RUBRICS = {
    "01.01.00": "1. SALUTATION",
    "01.02.00": "2. INVOCATION",
    "01.03.00": "3. PROLOGUE",
    "01.04.00": "4. GOD THE FATHER, GOD THE SON, GOD THE HOLY SPIRIT",
    "01.05.00": "5. POWER, WISDOM, AND LOVE",
    "01.06.00": "6. GREAT, SWIFT, AND BEAUTIFUL",
    "01.07.00": "7. THE NORTH POLE",
    "01.08.00": "8. THE OTHER POLE",
    "01.09.00": "9. THE STARS",
    "01.10.00": "10. THE ZODIAC",
    "01.11.00": "11. THE SIGNS AND THEIR COMPLEXIONS",
    "01.12.00": "12. THE SEVEN SPHERES, SATURN",
    "01.13.00": "13. SATURN",
    "01.14.00": "14. JUPITER",
    "01.15.00": "15. MARS",
    "01.16.00": "16. THE SUN",
    "01.18.00": "18. LIKENESS",
    "01.19.00": "19. COMPARISON",
    "01.20.00": "20. THE FATHER BEGETS THE SON",
    "01.21.00": "21. ON PAGANS, THEN CHRIST",
    "01.23.00": "23. VENUS",
    "01.24.00": "24. MERCURY",
    "01.25.00": "25. THE MOON",
    "01.26.00": "26. OBSCURING OF THE SUN",
    "01.27.00": "27. PHASES OF THE MOON",
    "01.28.00": "28. OBSCURING OF THE MOON",
    "01.29.00": "29. EFFECTS OF THE MOON",
    "01.31.00": "31. NATURAL ORDER",
    "01.32.00": "32. VARIOUS EFFECTS ON HUMANS",
    "01.33.00": "33. EFFECTS ON ERAS",
    "01.35.00": "35. ON THE SOUL",
    "02.01.00": "1. PREAMBLE",
    "02.02.00": "2. THE ELEMENTS",
    "02.03.00": "3. FIRE",
    "02.04.00": "4. AIR",
    "02.05.00": "5. WATER",
    "02.06.00": "6. EARTH",
    "02.07.00": "7. HELL",
    "02.08.00": "8. EFFECTS",
    "02.09.00": "9. ON AIR",
    "02.10.00": "10. SWAMPS",
    "02.11.00": "11. RAIN",
    "02.12.00": "12. MOUNTAINS",
    "02.13.00": "13. SNOW",
    "02.14.00": "14. HAIL AND THUNDER",
    "02.15.00": "15. WIND",
    "02.16.00": "16. OCEAN",
    "02.17.00": "17. THE EBB AND FLOW OF THE SEA",
    "02.18.00": "18. THE HORIZON",
    "02.19.00": "19. DAY AND NIGHT",
    "02.20.00": "20. HOURS AND TIME",
    "02.21.00": "21. SPRING",
    "02.23.00": "23. SUMMER",
    "02.24.00": "24. AUTUMN",
    "02.25.00": "25. WINTER",
    "02.26.00": "26. THE ELEMENTS",
    "02.27.00": "27. THE COMPLEXIONS",
    "02.28.00": "28. RED CHOLER",
    "02.29.00": "29. CHOLER",
    "02.30.00": "30. BLOOD",
    "02.31.00": "31. PHLEGM",
    "02.32.00": "32. MELANCHOLY",
    "02.33.00": "33. ON THE SOUL",
    "02.35.00": "35. WORLDLY GOODS",
    "03.01.00": "1. DESCRIPTION OF THE EARTH",
    "03.02.00": "2. ZONES",
    "03.03.00": "3. ON THE WINDS",
    "03.04.00": "4. THE CHART",
    "03.05.00": "5. THE COMPASS NEEDLE",
    "03.06.00": "6. THE SAILS",
    "03.07.00": "7. THE CLOCK",
    "03.11.00": "11. ABOUT THE EARTH",
    "03.13.00": "13. ON ADAM, 5200 YEARS AGO",
    "03.14.00": "14. ON ASIA",
    "03.15.00": "15. ON THE FOUR RIVERS",
    "03.16.00": "16. FRISON, TIGRIS, AND EUPHRATES",
    "03.19.00": "19. THE RED SEA",
    "03.21.00": "21. THE CASPIAN SEA",
    "03.22.00": "22. TAURIS",
    "03.25.00": "25. MORE SEAS",
    "03.26.00": "26. NINEVEH, BAGHDAD AND THE TOWER OF BABEL",
    "03.27.00": "27. THE INDIAN SEA",
    "03.29.00": "29. MECCA",
    "03.31.00": "31. EGYPT",
    "03.32.00": "32. CAIRO",
    "03.34.00": "34. THE ATLAS MOUNTAINS",
}


def populate_rubrics(apps, schema_editor):
    # data migration to populate rubrics
    StanzaTranslated = apps.get_model("manuscript", "StanzaTranslated")
    rubrics = StanzaTranslated.objects.filter(
        is_rubric=True, stanza_line_code_starts__in=RUBRICS.keys()
    )
    updated = []

    for rubric in rubrics:
        rubric.stanza_text = RUBRICS[rubric.stanza_line_code_starts]
        updated.append(rubric)

    StanzaTranslated.objects.bulk_update(updated, ["stanza_text"])


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0121_manuscriptfamily"),
    ]

    operations = [migrations.RunPython(populate_rubrics, migrations.RunPython.noop)]
