# Generated by Django 5.1.15 on 2026-02-09 18:33

from django.db import migrations, models


def clear_authority_files(apps, schema_editor):
    # clear out all non-WHG authority file records for places
    Location = apps.get_model("manuscript", "Location")
    Location.objects.exclude(authority_file__icontains="whgazetteer").update(
        authority_file=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0122_populate_rubrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="authority_file",
            field=models.URLField(
                blank=True,
                help_text="The URL to the World Historical Gazetteer link for the location. If there isn't one, leave blank.",
                max_length=255,
                null=True,
                verbose_name="WHG link",
            ),
        ),
        migrations.RunPython(clear_authority_files, migrations.RunPython.noop),
    ]
