# Generated by Django 5.1.15 on 2026-02-10 19:13

from django.db import migrations, models
from django.utils.text import slugify
from unidecode import unidecode


def populate_slugs(apps, schema_editor):
    Location = apps.get_model("manuscript", "Location")

    for location in Location.objects.all():
        if not location.slug:
            # generate a slug
            if location.name and location.name.strip():
                slug_src = location.name
            elif location.placename_id:
                slug_src = location.placename_id
            else:
                slug_src = f"toponym-{location.id}"
            base_slug = slugify(unidecode(str(slug_src)))
            slug = base_slug

            # dedupe
            counter = 1
            while Location.objects.filter(slug=slug).exclude(id=location.id).exists():
                counter += 1
                slug = f"{base_slug}-{counter}"

            # save
            location.slug = slug
            location.save()


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0123_alter_location_authority_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Short, durable, unique identifier for use in URLs. Save and continue editing to have a new slug autogenerated. Editing will change the public, citable URL for this entity.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
