# Generated by Django 5.1.15 on 2026-02-18 20:07

import django.db.models.deletion
from django.db import migrations, models


def delete_all_aliases(apps, schema_editor):
    LocationAlias = apps.get_model("manuscript", "LocationAlias")
    LocationAlias.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0124_location_slug"),
    ]

    operations = [
        migrations.RunPython(delete_all_aliases, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="locationalias",
            options={
                "verbose_name": "Toponym Alias",
                "verbose_name_plural": "Toponym Aliases",
            },
        ),
        migrations.AddField(
            model_name="locationalias",
            name="folio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.folio",
            ),
        ),
        migrations.AddField(
            model_name="locationalias",
            name="manuscript",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.singlemanuscript",
            ),
        ),
        migrations.RemoveField(
            model_name="locationalias",
            name="folios",
        ),
        migrations.RemoveField(
            model_name="locationalias",
            name="manuscripts",
        ),
        migrations.RemoveField(
            model_name="locationalias",
            name="placename_from_mss",
        ),
        migrations.RemoveField(
            model_name="locationalias",
            name="placename_standardized",
        ),
    ]
