# Generated by Django 5.1.15 on 2026-02-18 20:07

import django.db.models.deletion
from django.db import migrations, models


def migrate_and_clean_aliases(apps, schema_editor):
    LocationAlias = apps.get_model("manuscript", "LocationAlias")

    # delete placename_alias entries
    LocationAlias.objects.filter(
        (models.Q(placename_modern__isnull=True) | models.Q(placename_modern="")),
        (models.Q(placename_ancient__isnull=True) | models.Q(placename_ancient="")),
    ).exclude(
        models.Q(placename_alias__isnull=True) | models.Q(placename_alias="")
    ).delete()

    # keep placename_modern and placename_ancient entries
    to_update = []
    to_keep = LocationAlias.objects.prefetch_related("manuscripts", "folios").exclude(
        models.Q(placename_modern__isnull=True) | models.Q(placename_modern=""),
        models.Q(placename_ancient__isnull=True) | models.Q(placename_ancient=""),
    )

    # migrate to new LocationAlias.manuscript and LocaitonAlias.folio
    for alias in to_keep:
        # just use first related manuscript and folio
        old_ms = alias.manuscripts.first()
        old_folio = alias.folios.first()

        if old_ms or old_folio:
            alias.manuscript = old_ms
            alias.folio = old_folio
            to_update.append(alias)

    # bulk update
    if to_update:
        LocationAlias.objects.bulk_update(to_update, ["manuscript", "folio"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("manuscript", "0124_location_slug"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="locationalias",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="locationalias",
            name="folio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.folio",
            ),
        ),
        migrations.AddField(
            model_name="locationalias",
            name="manuscript",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.singlemanuscript",
            ),
        ),
        migrations.RunPython(migrate_and_clean_aliases, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="locationalias",
            options={
                "verbose_name": "Toponym Alias",
                "verbose_name_plural": "Toponym Aliases",
            },
        ),
        migrations.RemoveField(
            model_name="locationalias",
            name="folios",
        ),
        migrations.RemoveField(
            model_name="locationalias",
            name="manuscripts",
        ),
        migrations.RemoveField(
            model_name="locationalias",
            name="placename_from_mss",
        ),
        migrations.RemoveField(
            model_name="locationalias",
            name="placename_standardized",
        ),
    ]
