# Generated by Django 5.1.15 on 2026-03-03 18:03

from django.db import migrations, models


def migrate_modern_and_ancient(apps, schema_editor):
    # migrate all modern and ancient placenames to Location records
    LocationAlias = apps.get_model("manuscript", "LocationAlias")
    Location = apps.get_model("manuscript", "Location")

    to_migrate = LocationAlias.objects.exclude(
        models.Q(placename_modern__isnull=True) | models.Q(placename_modern=""),
        models.Q(placename_ancient__isnull=True) | models.Q(placename_ancient=""),
    )

    # group updates to prevent overwrites
    location_updates = {}

    for alias in to_migrate:
        loc_id = alias.location_id
        if not loc_id:
            continue

        # use sets to avoid duplication
        if loc_id not in location_updates:
            location_updates[loc_id] = {"modern": set(), "ancient": set()}

        if alias.placename_modern and alias.placename_modern.strip():
            location_updates[loc_id]["modern"].add(alias.placename_modern.strip())

        if alias.placename_ancient and alias.placename_ancient.strip():
            location_updates[loc_id]["ancient"].add(alias.placename_ancient.strip())

    for loc_id, data in location_updates.items():
        loc = Location.objects.get(pk=loc_id)

        # join into comma-separated strings
        modern_str = ", ".join(sorted(list(data["modern"])))
        ancient_str = ", ".join(sorted(list(data["ancient"])))

        if modern_str:
            loc.placename_modern = modern_str
        if ancient_str:
            loc.placename_ancient = ancient_str

        loc.save()

    LocationAlias.objects.filter(
        models.Q(placename_alias__isnull=True) | models.Q(placename_alias="")
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0125_alter_locationalias_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="placename_ancient",
            field=models.CharField(
                blank=True,
                help_text="The ancient name of the placename.",
                max_length=255,
                null=True,
                verbose_name="Ancient placename",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="placename_modern",
            field=models.CharField(
                blank=True,
                help_text="The modern name of the placename.",
                max_length=255,
                null=True,
                verbose_name="Modern placename",
            ),
        ),
        migrations.RunPython(migrate_modern_and_ancient, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="locationalias",
            name="placename_ancient",
        ),
        migrations.RemoveField(
            model_name="locationalias",
            name="placename_modern",
        ),
    ]
