# Generated by Django 5.1.15 on 2026-02-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0125_alter_locationalias_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="locationalias",
            unique_together=set(),
        ),
    ]
