# Generated by Django 5.1.15 on 2026-03-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0126_remove_locationalias_placename_ancient_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locationalias",
            options={
                "ordering": ["id"],
                "verbose_name": "Toponym Alias",
                "verbose_name_plural": "Toponym Aliases",
            },
        ),
        migrations.AlterField(
            model_name="locationalias",
            name="placename_alias",
            field=models.CharField(
                blank=True,
                help_text="An alias for the placename.",
                max_length=255,
                null=True,
                verbose_name="Alias",
            ),
        ),
    ]
