from django.core.files.storage import default_storage
from django.db import models
from wagtail import blocks
from wagtail.admin.panels import FieldPanel
from wagtail.contrib.routable_page.models import RoutablePageMixin
from wagtail.documents.blocks import DocumentChooserBlock
from wagtail.embeds.blocks import EmbedBlock
from wagtail.fields import RichTextField, StreamField
from wagtail.images.blocks import ImageChooserBlock
from wagtail.models import Page
from wagtail.snippets.models import register_snippet


class ImageBlock(blocks.StructBlock):
    image = ImageChooserBlock(required=True)
    caption = blocks.CharBlock(
        required=False, help_text="Optional caption for the image"
    )

    class Meta:
        icon = "image"
        template = "partials/image_block.html"


class CommonContentBlock(blocks.StreamBlock):
    paragraph = blocks.RichTextBlock(icon="pilcrow")
    heading = blocks.CharBlock(icon="title")
    image = ImageBlock()
    video = EmbedBlock(icon="media", max_width=800, max_height=400)


class AboutPage(RoutablePageMixin, Page):
    body = StreamField(CommonContentBlock(), use_json_field=True, blank=True)
    team = RichTextField(blank=True)

    content_panels = Page.content_panels + [
        FieldPanel("body", classname="full"),
        FieldPanel("team", classname="full"),
    ]
    template = "pages/about_page.html"


class SitePage(Page):
    body = StreamField(CommonContentBlock(), use_json_field=True, blank=True)
    content_panels = Page.content_panels + [
        FieldPanel("body", classname="full"),
    ]
    template = "pages/site_page.html"


class NavCardBlock(blocks.StructBlock):
    title = blocks.CharBlock(
        required=True,
        help_text="The title text that will appear in the card (e.g. Edition)",
    )
    description = blocks.TextBlock(
        required=True, help_text="The subtitle text that will appear in the card"
    )
    image = ImageChooserBlock(required=True)
    url = blocks.CharBlock(required=True, help_text="The URL for the 'More' link")

    class Meta:
        icon = "link"
        label = "Navigation Card"


@register_snippet
class HomeIntroduction(models.Model):
    title = models.CharField(max_length=255)
    body = StreamField(CommonContentBlock(), use_json_field=True, blank=True)
    navigation_cards = StreamField(
        [("card", NavCardBlock())],
        use_json_field=True,
        blank=True,
        help_text="The cards with links that appear below the intro text",
    )

    panels = [
        FieldPanel("title"),
        FieldPanel("body"),
        FieldPanel("navigation_cards"),
    ]

    def __str__(self):
        return self.title


@register_snippet
class ManuscriptsIntroduction(models.Model):
    title = models.CharField(max_length=255)
    body = RichTextField()

    panels = [
        FieldPanel("title"),
        FieldPanel("body"),
    ]

    def __str__(self):
        return self.title


class ExternalLinkBlock(blocks.StructBlock):
    """Block for adding external links to the data page"""

    title = blocks.CharBlock(required=True, help_text="Text to display for the link")
    url = blocks.URLBlock(required=True, label="URL")

    class Meta:
        icon = "link"
        label = "External Link"


class DocumentResourceBlock(blocks.StructBlock):
    """Block for adding document uploads to the data page"""

    title = blocks.CharBlock(
        required=False, help_text="Optional: Override the document's original filename"
    )
    document = DocumentChooserBlock(required=True)

    class Meta:
        icon = "doc-empty"
        label = "Uploaded File (PDF, etc.)"


class DataPage(SitePage):
    """Page type used only for the Data page"""

    template = "pages/data_page.html"

    additional_resources = StreamField(
        [
            ("link", ExternalLinkBlock()),
            ("document", DocumentResourceBlock()),
        ],
        use_json_field=True,
        blank=True,
    )

    content_panels = SitePage.content_panels + [
        FieldPanel("additional_resources", heading="Additional Resources"),
    ]

    def get_context(self, request):
        """add our public export URLs to context to include in the template"""
        context = super().get_context(request)
        files = [
            ("Manuscripts", "manuscripts"),
            ("Folios", "folios"),
            ("Stanzas (Italian)", "stanzas"),
            ("Stanzas (English)", "translated_stanzas"),
            ("Textual Variants", "textual_variants"),
            ("Toponyms", "toponyms"),
            ("Toponym Variants", "toponym_variants"),
        ]
        export_list = []
        for label, slug in files:
            file_path = f"exports/{slug}.csv"
            # Use default_storage to generate the safe S3 URL
            # Fallback to '#' if the file hasn't been generated by the command yet
            if default_storage.exists(file_path):
                file_url = default_storage.url(file_path)
                export_list.append(
                    {
                        "label": label,
                        "csv": file_url,
                    }
                )
        context["exports"] = export_list
        return context
